# Generated by Django 4.2.7 on 2023-11-26 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 13, 39, 58, 294046), verbose_name='дата публикации'),
        ),
    ]
