# Generated by Django 4.2.7 on 2023-11-27 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 12, 10, 58, 820102), verbose_name='дата публикации'),
        ),
    ]
