# Generated by Django 4.2.7 on 2023-11-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='полное имя')),
                ('mail', models.CharField(max_length=150, verbose_name='почта')),
                ('phone', models.IntegerField(verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=150, verbose_name='услуги')),
                ('content', models.TextField(verbose_name='контент')),
                ('photo', models.ImageField(default='no photo', upload_to='med_services', verbose_name='изображения')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medcenter.doctors', verbose_name='врачи')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
