# Generated by Django 4.2.7 on 2023-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='должность'),
        ),
    ]
