# Generated by Django 4.2.7 on 2023-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcenter', '0002_doctors_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='номер телефона'),
        ),
    ]
