# Generated by Django 4.2.7 on 2023-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='номер телефона'),
        ),
    ]
